### PR TITLE
Adding RSA SHA256

### PR DESCRIPTION
**Pull request by obihann**
Based on issue #4 I have started work on adding support for RSA SHA256.

### CODE REVIEW

**Comment by obihann** [comment]
Just a heads up this is a placeholder and not 100% complete yet. I'm having some issues generating the key however. 

@jasongoodwin if you want to take a look and point out my stupidity that would be greatly appreachaited. I started following the [example](http://www.java2s.com/Tutorial/Java/0490__Security/RSASignatureGeneration.htm) you provided however I wasn't 100% able to use it since that seems to generate a key from scratch, and we are accepting a key from the user. 

Thanks.

**Comment by jasongoodwin** [comment]
Hey thanks so much - I'm sorry I haven't been on getting this in myself - started new role and have been trying to finish up a book. I'll check this out later - I'm sure we can nail it down. Thanks for the contribution.

**Comment by obihann** [comment]
No problem at all, glad I could help (hopefully my code is helpful lol). I'm still new to scala so I have a feeling some of my issues are a lack of knowledge. Thanks!

**Comment by jasongoodwin** [comment]
Hey, I'd like to merge this into another branch to be able to add to it - do you think that you can:
1) Rebase master (it has another change)
2) Make the PR targeting another branch (if possible? I've never done it)
You can call the branch whatever you like. RSA is a bit different so I'd like to spend some time w/ this request this week and get it in - it's quite highly requested.

**Comment by obihann** [comment]
I'll take care of that and start a new PR for you.

**Comment by jasongoodwin** [comment]
Thanks so much - sorry - it might be possible for me to do it but I want you to get credit for the merge/commit.

**Comment by obihann** [comment]
@jasongoodwin Do you want to create a `develop` branch or something similar, so that I can create the pull request? Or would you like me to create a pull request to the `revert 3` branch? I've rebaed from your `master` branch so I'm ready to go :+1:

**Comment by jasongoodwin** [comment]
Sure that's fine. Develop branch, or rsa branch or something like that.

**Comment by obihann** [comment]
hey @jasongoodwin your going to have to create that branch, I can only create a pull request to existing branches

**Comment by jasongoodwin** [comment]
sorry! It's done.

**Comment by obihann** [comment]
Thanks, pull request is in.

**Comment by jasongoodwin** [comment]
thanks - merged it in. 
I'll validate it does what it says on the tin and then release - this is requested quite a lot.
Thanks again!

**Pull request closed without merging**
